### ISSUE TITLE
still an n+1 issue hanging around...

### ISSUE THREAD

**Issue by snlamm** [learn-co-curriculum/rails-5-json-api#1]
After implementing the app, I noticed there were still some extraneous database hits. Using the bullet gem, I solved it by configuring controllers/api/v1/cats_controller.rb as such (i.e. by adding ', include: ['cats']'):

module Api
  module V1
    class CatsController < ApplicationController

```
  def index
    render json: Cat.includes(:hobbies), include: ['hobbies'], include: ['cats']
  end

end
```

  end
end

Using a 4 record seed db, I saved 10 miliseconds this way ! : )

**Comment by realAndrewCohn** [comment]
addressed by 21591fcf29d95cebf7b8f58963bd88ccff2bd55f
